### ISSUE TITLE
Table 'surface.scanners_rootbox' doesn't exis

### ISSUE THREAD

**Issue by cristian-serban-tvp** [surface-security/surface#25]
I've installed the docker version as detailed in the README. 
I get the following errors:
dev-resync-rootbox-1  | django.db.utils.ProgrammingError: (1146, "Table 'surface.scanners_rootbox' doesn't exist")

Please advise.

Full Trace
dev-resync-rootbox-1  | Traceback (most recent call last):
dev-resync-rootbox-1  |   File "/surface/surface/./manage.py", line 22, in <module>
dev-resync-rootbox-1  |     main()
dev-resync-rootbox-1  |   File "/surface/surface/./manage.py", line 18, in main
dev-resync-rootbox-1  |     execute_from_command_line(sys.argv)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
dev-resync-rootbox-1  |     utility.execute()
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
dev-resync-rootbox-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
dev-resync-rootbox-1  |     self.execute(*args, **cmd_options)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/logbasecommand/base.py", line 64, in execute
dev-resync-rootbox-1  |     super().execute(*args, **options)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
dev-resync-rootbox-1  |     output = self.handle(*args, **options)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/database_locks/locks.py", line 126, in new_handle
dev-resync-rootbox-1  |     return orig_handle(self, *args, **kwargs)
dev-resync-rootbox-1  |   File "/surface/surface/scanners/management/commands/resync_rootbox.py", line 181, in handle
dev-resync-rootbox-1  |     for rootbox in rootboxes:
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
dev-resync-rootbox-1  |     self._fetch_all()
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
dev-resync-rootbox-1  |     self._result_cache = list(self._iterable_class(self))
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
dev-resync-rootbox-1  |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
dev-resync-rootbox-1  |     cursor.execute(sql, params)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
dev-resync-rootbox-1  |     return super().execute(sql, params)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
dev-resync-rootbox-1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
dev-resync-rootbox-1  |     return executor(sql, params, many, context)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
dev-resync-rootbox-1  |     return self.cursor.execute(sql, params)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
dev-resync-rootbox-1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
dev-resync-rootbox-1  |     return self.cursor.execute(sql, params)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
dev-resync-rootbox-1  |     return self.cursor.execute(query, args)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
dev-resync-rootbox-1  |     res = self._query(query)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
dev-resync-rootbox-1  |     db.query(q)
dev-resync-rootbox-1  |   File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
dev-resync-rootbox-1  |     _mysql.connection.query(self, query)
dev-resync-rootbox-1  | django.db.utils.ProgrammingError: (1146, "Table 'surface.scanners_rootbox' doesn't exist")

**Comment by gsilvapt** [comment]
Hi @cristian-serban-tvp,

Thanks for reaching out! Did you run any additional commands other than the ones specified in the `README`?
